config/routes.rb
Kurbi2::Application.routes.draw do
  
  root :to => 'pages#home'
  
  match '/about',   :to => 'pages#about',       :as => 'about'
  match '/home',    :to => 'pages#home',        :as => 'home'
  match '/contact', :to => 'pages#contact',     :as => 'contact' 
  match '/signup',  :to => 'patients#new',      :as => 'signup'
  match '/signin',  :to => 'sessions#new',      :as => 'signin'
  match '/signout', :to => 'sessions#destroy',  :as => 'signout'

  match '/admin', :to => 'admins#index', :as => 'admin'
  match '/admin/symptom_categories/index', :to => 'symptom_categories#index', :as => 'admin_list_categories'
  match '/admin/symptom_categories/new', :to => 'symptom_categories#new', :as => 'admin_new_categories'
  match '/admin/predefined_symptoms/index', :to => 'predefined_symptoms#index', :as => 'admin_list_symptoms'
    
  resources :surveys 
  match '/surveys/:patient_id/more', :to => 'surveys#more'
     	
  resources :sessions, :only => [:new, :create, :destroy]
  resources :password_resets   

  resources :patients
  match '/patients/:id/edit/profile', :to => 'patients#profile', :as => 'profile'
  match '/patients/:id/careteam', :to => 'patients#careteam', :as => 'careteam'
  
  resources :symptoms
  
  resources :symptom_categories
  
  resources :daily_record_details
  
  resources :daily_records
  
  resources :notes
  
  resources :search_phrases
  
  resources :searches
  
  resources :patient_groups
  
  resources :addresses
  
  resources :notifications
  
  resources :action_confirmations
  
  resources :actions

#  resources :system_errors

#  resources :severities

#  resources :patient_symptom_searches  

#  resources :pages

#  resources :messages

#  resources :disease_profiles

#  resources :days

#  resources :addresses

#  resources :actions
end

app/models/action.rb
class Action < ActiveRecord::Base
end

app/models/address.rb
class Address < ActiveRecord::Base
end

app/models/daily_record.rb
class DailyRecord < ActiveRecord::Base
end

app/models/day.rb
class Day < ActiveRecord::Base
	has_many :daily_record
	has_many :patient, :through => :daily_record
end

app/models/ip_address.rb
class IpAddress < ActiveRecord::Base
  belongs_to :patient
end

app/models/message.rb
class Message < ActiveRecord::Base
	has_and_belongs_to_many :person
end

app/models/note.rb
class Note < ActiveRecord::Base
end

app/models/notification.rb
class Notification < ActiveRecord::Base
end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/patient.rb
class Patient < ActiveRecord::Base
	has_many				        :notifications
	has_many			          :messages, :through => :notifications
	has_many				        :action_confirmations
	has_many				        :actions, :through => :action_confirmations
	has_and_belongs_to_many :addresses
	
	has_and_belongs_to_many	:patient_groups
	
	has_many				        :daily_records
	has_many 				        :daily_record_details, :through => :daily_records
	has_many				        :symptoms, :through => :daily_records
	has_many				        :days, :through => :daily_records
	
	has_many				        :searches
	has_many				        :search_phrases, :through => :searches
	
	has_many				        :notes, :through => :daily_records
	
	has_many				        :surveys
	has_many				        :symptoms, :through => :surveys
	
	attr_accessible :first_name, :last_name, :email, :birthday, :location, :race, :sex, 
					        :first_occurrence, :year_diagnosed, :condition, :primary_physician, :medications, 
					        :other_medications, :photo, :password, :password_confirmation 
		
	validates :first_name, :presence => true, :length => { :maximum => 50 }
	validates :last_name,  :presence => true, :length => { :maximum => 50 }
	
	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, :format => { :with => email_regex },
					          :uniqueness => { :case_sensitive => false }
	has_secure_password
	validates :password, :confirmation => true
	
	has_attached_file :photo, :styles => { :small => "95x83>" },
						        :url  => "/assets/patients/:id/:style/:basename.:extension",
	                  :path => ":rails_root/public/assets/patients/:id/:style/:basename.:extension"
	
	validates_attachment_size         :photo, :less_than => 5.megabytes
	validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png', 'image/gif', 'image/tiff']
	                    	
	before_create { generate_token(:auth_token) }                  
	
	def to_param
		"#{id} #{first_name + " " + last_name}".parameterize
	end
	
	def send_password_reset
		generate_token(:password_reset_token)
		self.password_reset_sent_at = Time.zone.now
		save!
		PatientMailer.password_reset(self).deliver
	end
	
	def generate_token(column)
		begin
			self[column] = SecureRandom.urlsafe_base64
		end while Patient.exists?(column => self[column])
	end	
end

app/models/patient_group.rb
class PatientGroup < ActiveRecord::Base
end

app/models/search.rb
class Search < ActiveRecord::Base
end

app/models/search_phrase.rb
class SearchPhrase < ActiveRecord::Base
end

app/models/severity.rb
class Severity < ActiveRecord::Base
	belongs_to :daily_record
	belongs_to :predefined_symptom
end

app/models/survey.rb
class Survey < ActiveRecord::Base
end

app/models/survey_symptom.rb
class SurveySymptom < ActiveRecord::Base
end

app/models/symptom.rb
class Symptom < ActiveRecord::Base
	belongs_to :symptom_category
	
	attr_accessible :name, :description, :symptom_category_id
	
	def to_param
		"#{id} #{name}".parameterize
	end
end

app/models/system_error.rb
class SystemError < ActiveRecord::Base
end

app/helpers/pages_helper.rb
module PagesHelper
	def signin_btn
		image_tag("kurbi-signin-btn.png")
	end
	
	def signout_btn
		image_tag("kurbi-signout-btn.png")
	end
	
	def kurbi_pic
		image_tag("kurbi-pic.png")
	end
	
	def wes_pic 
		image_tag("wes-pic.gif")
	end
	
	def steve_pic
		image_tag("steve-pic.gif")
	end
	
	def david_pic
		image_tag("dave-pic.gif")
	end
	
	def matt_pic
		image_tag("matt-pic.gif")
	end
	
	def twitter
		image_tag("twitter.gif", :alt => "Go Kurbi Twitter")
	end
	
	def tumblr
		image_tag("tumblr.gif", :alt => "Kurbi Mobile Health Tumblr Blog")
	end
	
	def facebook 
		image_tag("facebook.gif", :alt => "Kurbi Mobile Health Facebook Profile")
	end
	
	def home_image
		image_tag("main-image.png")
	end
	
	def img_symptom_tracking
		image_tag("Kurbi_Journal.png")
	end
	
	def img_symptom_charting
		image_tag("Kurbi_Report.png")
	end
	
	def img_symptom_sharing
		image_tag("Patients_Report.png")
	end
end

app/helpers/surveys_helper.rb
module SurveysHelper

	def show_more_button
		image_tag("show-more-button.png")
	end
	
	def symptom_plus
		image_tag("symptom-plus.png")
	end
	
	def symptom_minus
		image_tag("symptom-minus.png")
	end
	
	def auto_update_btn
		image_tag("auto-update-btn.png")
	end
	
	def symptom_search
		image_tag("symptom-search.png")
	end
end

app/views/admins/index.html.erb
<h1>Admin</h1>

<p><%= link_to "Admin Home", admin_path %></p>

<table id="admin_table">
  <!-- ROW 1 -->
  <tr>
    <th>
      <h3>Symptom Categories</h3>
      <p>Number of Categories: <%= @categories.count %></p>
      <p><%= link_to "All Symptom Categories", admin_list_categories_path  %></p>
    </th>
    <th>
      <h3>Symptoms</h3>
      <p>Number of Symptoms: <%= @symptoms.count %></p>
      <p><%= link_to "All Symptoms", admin_list_symptoms_path %></p>
    </th>
  </tr>  
  <!-- ROW 2 -->
  <tr>
    <th>
      <h3>Users</h3>
      <p>Number of Users: <%= @users.count %></p>
      <p><%= link_to "All Users", patients_path %></p>
    </th>
    <th>
      <h3>All Daily Records</h3>
      <p>Number: <%= @dailyrecords.count %></p>
      <p>--</p>
    </th>
  </tr>
</table>

app/views/shared/_profile_sidebar.html.erb
<div class="profile-info">
	<h2><%= link_to current_patient.first_name + " " + current_patient.last_name, current_patient %></h2>
	<% if current_patient.photo? %>
		<%= image_tag current_patient.photo.url(:small), :class => "round mid-shadow" %>
	<% else %>
		<%= profile_image %>
	<% end %>
</div><!--/ .profile_info-->
<ul class="nav nav-tabs nav-stacked">
	<li><%= link_to "View Profile", current_patient %></li>
	<li><%= link_to "Edit Profile", profile_path %></li>
	<li><%= link_to "Account Settings", edit_patient_path(current_patient) %></li>
	<li><%= link_to "Care Team", careteam_path %></li>
</ul>

app/views/shared/_sidenav.html.erb
<nav id="main-sidebar">
	<ul class="side-nav-style">
		<li class="<%= "current" if params[:controller] == "surveys" %>">
			<%= link_to "Journal", survey_path %>
		</li>
		<li class="<%= "current" if params[:controller] == "histories" %>">
			<%= link_to "History", history_path %>
		</li>
		<li class="<%= "current" if params[:controller] == "patients" %>">
			<%= link_to "Profile", @patient %>
		</li>
	</ul>
</nav>