config/routes.rb
Kurbi2::Application.routes.draw do
  
  root :to => 'pages#home'
  
  match '/about',   :to => 'pages#about',       :as => 'about'
  match '/home',    :to => 'pages#home',        :as => 'home'
  match '/contact', :to => 'pages#contact',     :as => 'contact' 
  match '/signup',  :to => 'patients#new',      :as => 'signup'
  match '/signin',  :to => 'sessions#new',      :as => 'signin'
  match '/signout', :to => 'sessions#destroy',  :as => 'signout'

  match '/admin', :to => 'admins#index', :as => 'admin'
  match '/admin/symptom_categories/index', :to => 'symptom_categories#index', :as => 'admin_list_categories'
  match '/admin/symptom_categories/new', :to => 'symptom_categories#new', :as => 'admin_new_categories'
  match '/admin/predefined_symptoms/index', :to => 'predefined_symptoms#index', :as => 'admin_list_symptoms'
    
  resources :surveys 
  match '/surveys/:patient_id/more', :to => 'surveys#more'
     	
  resources :sessions, :only => [:new, :create, :destroy]
  resources :password_resets   

  resources :patients
  match '/patients/:id/edit/profile', :to => 'patients#profile', :as => 'profile'
  match '/patients/:id/careteam', :to => 'patients#careteam', :as => 'careteam'
  
  resources :symptoms
  
  resources :symptom_categories
  
  resources :daily_record_details
  
  resources :daily_records
  
  resources :notes
  
  resources :search_phrases
  
  resources :searches
  
  resources :patient_groups
  
  resources :addresses
  
  resources :notifications
  
  resources :action_confirmations
  
  resources :actions

#  resources :system_errors

#  resources :severities

#  resources :patient_symptom_searches  

#  resources :pages

#  resources :messages

#  resources :disease_profiles

#  resources :days

#  resources :addresses

#  resources :actions
end

app/models/symptom_category.rb
class SymptomCategory < ActiveRecord::Base
	has_many :symptoms
	
	attr_accessible :name, :description
	
	def to_param
		"#{id} #{name}".parameterize
	end

end

app/controllers/symptom_categories_controller.rb
class SymptomCategoriesController < ApplicationController
  # GET /symptom_categories
  # GET /symptom_categories.json
  def index
    @symptom_categories = SymptomCategory.all
	@title = "Symptom Categories"
	
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @symptom_categories }
    end
  end

  # GET /symptom_categories/1
  # GET /symptom_categories/1.json
  def show
    @symptom_category = SymptomCategory.find(params[:id])
    @title = @symptom_category.name

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @symptom_category }
    end
  end

  # GET /symptom_categories/new
  # GET /symptom_categories/new.json
  def new
    @symptom_category = SymptomCategory.new
    @title = "New Symptom Category"

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @symptom_category }
    end
  end

  # GET /symptom_categories/1/edit
  def edit
    @symptom_category = SymptomCategory.find(params[:id])
    @title = "Edit Symptom Category"
  end

  # POST /symptom_categories
  # POST /symptom_categories.json
  def create
    @symptom_category = SymptomCategory.new(params[:symptom_category])

    respond_to do |format|
      if @symptom_category.save
        format.html { redirect_to @symptom_category, notice: 'Symptom category was successfully created.' }
        format.json { render json: @symptom_category, status: :created, location: @symptom_category }
      else
        format.html { render action: "new" }
        format.json { render json: @symptom_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /symptom_categories/1
  # PUT /symptom_categories/1.json
  def update
    @symptom_category = SymptomCategory.find(params[:id])

    respond_to do |format|
      if @symptom_category.update_attributes(params[:symptom_category])
        format.html { redirect_to @symptom_category, notice: 'Symptom category was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @symptom_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /symptom_categories/1
  # DELETE /symptom_categories/1.json
  def destroy
    @symptom_category = SymptomCategory.find(params[:id])
    @symptom_category.destroy

    respond_to do |format|
      format.html { redirect_to symptom_categories_url }
      format.json { head :ok }
    end
  end
end

app/views/symptom_categories/_form.html.erb
<%= simple_form_for @symptom_category, :html => { :class => 'form-vertical' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Symptom Category</legend>
	<%= f.input :name, :label => "Category" %>
	<%= f.input :description %>
    <div class="form-actions">
	    <%= f.submit nil, :class => 'btn btn-success' %>
	    <%= link_to 'Cancel', symptom_categories_path, :class => 'btn' %>
	</div><!--/ .form-actions-->    
  </fieldset>
<% end %>

app/views/symptom_categories/index.html.erb
<legend>Symptom Categories</legend>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Category</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @symptom_categories.each do |symptom_category| %>
      <tr>
        <td><%= symptom_category.id %></td>
        <td><%= link_to symptom_category.name, symptom_category_path(symptom_category) %></td>
        <td>
          <%= link_to 'Edit', edit_symptom_category_path(symptom_category), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', symptom_category_path(symptom_category), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_symptom_category_path, :class => 'btn btn-success' %>

app/views/symptom_categories/show.html.erb
<legend>Symptom Category</legend>

<p>
  <b>Category</b><br>
  <%= @symptom_category.name %>
</p>

<% if @symptom_category.description? == true %>
<p>
  <b>Description</b><br>
  <%= @symptom_category.description %>
</p>
<% end %>

<div class="form-actions">
  <%= link_to 'Back', symptom_categories_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_symptom_category_path(@symptom_category), :class => 'btn' %>
  <%= link_to 'Delete', symptom_category_path(@symptom_category), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>